create table public.content_settings (
  id smallint primary key default 1 check (id = 1),
  brand_name text not null default '6CAT Academy' check (char_length(trim(brand_name)) between 1 and 120),
  audience text not null default 'คนทำงาน เจ้าของธุรกิจ และผู้เริ่มต้นที่อยากทำเว็บไซต์ได้ด้วยตัวเอง',
  brand_voice text not null default 'เป็นกันเอง ชัดเจน ให้ความรู้แบบลงมือทำได้จริง ไม่ขายเกินจริง',
  business_context text not null default '6CAT Academy สอนทำเว็บไซต์: Online Course 990 บาท, Private Live Online 2,999 บาท, Solo Workshop 3,999 บาท และ Buddy Workshop 5,999 บาท',
  default_cta text not null default 'ดูรายละเอียดคอร์สและเลือกแพ็กเกจที่เหมาะกับคุณ',
  content_pillars text[] not null default array['ความรู้ทำเว็บไซต์', 'ตัวอย่างและแรงบันดาลใจ', 'เบื้องหลังการสอน', 'แนะนำคอร์ส', 'ชวนพูดคุย']::text[],
  avoid_topics text not null default 'หลีกเลี่ยงการรับประกันรายได้ ผลลัพธ์เกินจริง และข้อมูลราคาที่ไม่ตรงกับหน้าเว็บไซต์',
  posts_per_day smallint not null default 1 check (posts_per_day between 1 and 2),
  morning_time time without time zone not null default '10:00',
  evening_time time without time zone not null default '19:00',
  timezone text not null default 'Asia/Bangkok' check (timezone = 'Asia/Bangkok'),
  facebook_page_id text check (facebook_page_id is null or facebook_page_id ~ '^[0-9]{5,30}$'),
  facebook_page_name text check (facebook_page_name is null or char_length(trim(facebook_page_name)) between 1 and 160),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.content_settings (id) values (1);

create table public.content_posts (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  planned_date date not null,
  slot_number smallint not null check (slot_number between 1 and 2),
  scheduled_at timestamptz not null,
  title text not null check (char_length(trim(title)) between 1 and 180),
  content_type text not null default 'education'
    check (content_type in ('education', 'inspiration', 'behind_the_scenes', 'promotion', 'engagement')),
  objective text not null default '' check (char_length(objective) <= 1000),
  caption text not null default '' check (char_length(caption) <= 12000),
  cta text not null default '' check (char_length(cta) <= 1000),
  image_brief text not null default '' check (char_length(image_brief) <= 4000),
  image_prompt text not null default '' check (char_length(image_prompt) <= 8000),
  image_path text check (image_path is null or (char_length(image_path) between 1 and 500 and image_path !~ '\\.\\.')),
  image_required boolean not null default false,
  source text not null default 'manual' check (source in ('manual', 'ai')),
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'publishing', 'published', 'failed')),
  revision integer not null default 1 check (revision > 0),
  approved_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  published_at timestamptz,
  external_post_id text,
  external_post_url text check (external_post_url is null or external_post_url ~ '^https://([A-Za-z0-9-]+\.)*facebook\.com/'),
  publish_attempts smallint not null default 0 check (publish_attempts between 0 and 100),
  last_error text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (planned_date, slot_number),
  check (week_start = planned_date - ((extract(isodow from planned_date)::integer - 1) * interval '1 day')),
  check (
    (status in ('scheduled', 'publishing', 'published', 'failed') and approved_at is not null)
    or status = 'draft'
  )
);

create index content_posts_week_idx
  on public.content_posts (week_start, scheduled_at)
  include (status);

create index content_posts_due_idx
  on public.content_posts (scheduled_at)
  where status = 'scheduled';

create index content_posts_created_by_idx on public.content_posts (created_by);
create index content_posts_approved_by_idx on public.content_posts (approved_by);

create table public.content_publish_logs (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.content_posts(id) on delete cascade,
  event_type text not null check (event_type in ('publishing', 'published', 'failed')),
  message text,
  external_post_id text,
  created_at timestamptz not null default now()
);

create index content_publish_logs_post_idx
  on public.content_publish_logs (post_id, created_at desc);

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.guard_content_post_update()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  publishable_fields_changed boolean :=
    new.planned_date is distinct from old.planned_date
    or new.scheduled_at is distinct from old.scheduled_at
    or new.title is distinct from old.title
    or new.content_type is distinct from old.content_type
    or new.objective is distinct from old.objective
    or new.caption is distinct from old.caption
    or new.cta is distinct from old.cta
    or new.image_brief is distinct from old.image_brief
    or new.image_prompt is distinct from old.image_prompt
    or new.image_path is distinct from old.image_path
    or new.image_required is distinct from old.image_required;
begin
  if old.status = 'published' then
    raise exception 'โพสต์ที่เผยแพร่แล้วแก้ไขไม่ได้';
  end if;

  if old.status = 'publishing' and publishable_fields_changed then
    raise exception 'โพสต์กำลังถูกเผยแพร่ กรุณารอหรือตรวจสอบสถานะก่อนแก้ไข';
  end if;

  if publishable_fields_changed then
    new.status := 'draft';
    new.approved_at := null;
    new.approved_by := null;
    new.last_error := null;
  end if;

  new.revision := old.revision + 1;
  new.updated_at := now();
  return new;
end;
$$;

create trigger guard_content_post_update
before update on public.content_posts
for each row execute function private.guard_content_post_update();

create or replace function public.reconcile_content_post(
  p_post_id uuid,
  p_revision integer,
  p_published boolean,
  p_external_post_url text default null
)
returns setof public.content_posts
language plpgsql
security invoker
set search_path = ''
as $$
declare
  affected integer;
begin
  if coalesce(auth.jwt() ->> 'email', '') <> 'admin@6cat.com' then
    raise exception 'ไม่มีสิทธิ์จัดการคอนเทนต์';
  end if;
  if p_external_post_url is not null and p_external_post_url !~ '^https://([A-Za-z0-9-]+\.)*facebook\.com/' then
    raise exception 'ลิงก์โพสต์ Facebook ไม่ถูกต้อง';
  end if;

  return query
  update public.content_posts
  set
    status = case when p_published then 'published' else 'draft' end,
    approved_at = case when p_published then approved_at else null end,
    approved_by = case when p_published then approved_by else null end,
    published_at = case when p_published then now() else null end,
    external_post_url = case when p_published then p_external_post_url else null end,
    last_error = null
  where id = p_post_id
    and status = 'publishing'
    and revision = p_revision
    and updated_at <= now() - interval '5 minutes'
  returning *;

  get diagnostics affected = row_count;
  if affected <> 1 then
    raise exception 'โพสต์ยังทำงานอยู่ หรือสถานะถูกเปลี่ยนจากหน้าจออื่นแล้ว กรุณาโหลดใหม่';
  end if;
end;
$$;

revoke all on function public.reconcile_content_post(uuid, integer, boolean, text) from public, anon;
grant execute on function public.reconcile_content_post(uuid, integer, boolean, text) to authenticated;

alter table public.content_settings enable row level security;
alter table public.content_posts enable row level security;
alter table public.content_publish_logs enable row level security;

create policy "Admin can read content settings"
on public.content_settings
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can update content settings"
on public.content_settings
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@6cat.com')
with check ((auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can read content posts"
on public.content_posts
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can create content posts"
on public.content_posts
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can update content posts"
on public.content_posts
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@6cat.com')
with check ((auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can read content publish logs"
on public.content_publish_logs
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@6cat.com');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('content-assets', 'content-assets', false, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy "Admin can view content assets"
on storage.objects
for select
to authenticated
using (bucket_id = 'content-assets' and (auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can upload content assets"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'content-assets' and (auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can update content assets"
on storage.objects
for update
to authenticated
using (bucket_id = 'content-assets' and (auth.jwt() ->> 'email') = 'admin@6cat.com')
with check (bucket_id = 'content-assets' and (auth.jwt() ->> 'email') = 'admin@6cat.com');

create policy "Admin can delete content assets"
on storage.objects
for delete
to authenticated
using (bucket_id = 'content-assets' and (auth.jwt() ->> 'email') = 'admin@6cat.com');
